---
apiVersion: v1
kind: Service
metadata:
  name: cortex-alertmanager
spec:
  ports:
    - port: 80
  selector:
    app: contex-alertmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex-alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cortex-alertmanager
      release: cortex
  template:
    metadata:
      labels:
        app: cortex-alertmanager
        release: cortex
    spec:
      tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: cortex
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dedicated
                operator: In
                values:
                - cortex
      containers:
      - name: alertmanager
        image: quay.io/cortexproject/cortex:v0.4.0
        imagePullPolicy: IfNotPresent
        args:
        - -target=alertmanager
        - -log.level=debug
        - -server.http-listen-port=80
        - -alertmanager.configs.url=http://cortex-configs.cortex.svc.cluster.local:80
        - -alertmanager.web.external-url=/api/prom/alertmanager
        ports:
        - containerPort: 80
