---
apiVersion: v1
kind: Service
metadata:
  name: cortex-configs
spec:
  ports:
    - port: 80
  selector:
    app: cortex-configs

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex-configs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cortex-configs
      release: cortex
  template:
    metadata:
      labels:
        app: cortex-configs
        release: cortex
    spec:
      tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: cortex
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dedicated
                operator: In
                values:
                - cortex
      containers:
      - name: configs
        image: quay.io/cortexproject/cortex:v0.4.0
        imagePullPolicy: IfNotPresent
        args:
        - -target=configs
        - -server.http-listen-port=80
        - -database.uri=postgres://postgres@cortex-configs-db.cortex.svc.cluster.local/configs?sslmode=disable
        - -database.migrations=/migrations
        ports:
        - containerPort: 80
