---
apiVersion: v1
kind: Service
metadata:
  name: cortex-configs-db
spec:
  ports:
    - port: 5432
  selector:
    app: cortex-configs-db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex-configs-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cortex-configs-db
  template:
    metadata:
      labels:
        app: cortex-configs-db
      annotations:
        prometheus.io.scrape: "false"
    spec:
      tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: cortex
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dedicated
                operator: In
                values:
                - cortex
      containers:
      - name: configs-db
        image: postgres:9.6
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_DB
            value: configs
        ports:
        - containerPort: 5432
