---
# Source: cortex/templates/distributor-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: cortex-cortex-distributor
  labels:
    chart: cortex-0.0.1
    release: cortex
    heritage: Helm
    cortex: distributor
spec:
  ports:
    - port: 80
      name: http
      targetPort: http
  selector:
    app: cortex-distributor
    release: cortex
---
# Source: cortex/templates/distributor-dep.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex-cortex-distributor
  labels:
    chart: cortex-0.0.1
    release: cortex
    heritage: Helm
    cortex: distributor
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: cortex-distributor
      release: cortex
  template:
    metadata:
      labels:
        app: cortex-distributor
        release: cortex
        cortex: distributor
      annotations:
        prometheus.io/port: "80"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "false"
    spec:
      tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: cortex
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dedicated
                operator: In
                values:
                - cortex
      containers:
      - name: distributor
        image: "quay.io/cortexproject/distributor:master-79bba2f9"
        imagePullPolicy: IfNotPresent
        args:
        - -log.level=debug
        - -server.http-listen-port=80
        - -consul.hostname=cortex-cortex-consul:8500
        - -distributor.replication-factor=3
        ports:
        - containerPort: 80
          name: http
        #resources:
        # limits:
        #   cpu: 4
        # requests:
        #   cpu: 4
        #   memory: 4Gi
