---
# Source: cortex/templates/dynamodb-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: cortex-cortex-dynamodb
  labels:
    chart: cortex-0.0.1
    release: cortex
    heritage: Helm
spec:
  ports:
    - port: 8000
  selector:
    app: cortex-dynamodb
    release: cortex
---
# Source: cortex/templates/dynamodb-dep.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex-cortex-dynamodb
  labels:
    chart: cortex-0.0.1
    release: cortex
    heritage: Helm
    cortex: dynamodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cortex-dynamodb
      release: cortex
  template:
    metadata:
      labels:
        app: cortex-dynamodb
        release: cortex
        cortex: dynamodb
      annotations:
        prometheus.io.scrape: "false"
        sidecar.istio.io/inject: "false"
    spec:
      tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: cortex
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dedicated
                operator: In
                values:
                - cortex
      containers:
      - name: dynamodb
        image: "deangiberson/aws-dynamodb-local:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
